# Generated by Django 2.2.6 on 2019-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClsCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=5)),
                ('seccion', models.CharField(max_length=5)),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
