# Generated by Django 2.2.6 on 2019-10-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppEstablecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClsUsuario',
            fields=[
                ('pk_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=12)),
                ('estado', models.IntegerField()),
                ('fk_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEstablecimiento.ClsEstablecimiento')),
            ],
        ),
    ]
