# Generated by Django 2.2.6 on 2019-10-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsusuario',
            name='usuario',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
