# Generated by Django 2.2.6 on 2019-11-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0004_auto_20191031_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clsusuario',
            name='accesso',
        ),
    ]
