# Generated by Django 2.2.6 on 2019-10-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppProfesor', '0001_initial'),
        ('AppCarrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClsCurso',
            fields=[
                ('pk_curso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('fk_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCarrera.ClsCarrera')),
                ('fk_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProfesor.ClsProfesor')),
            ],
        ),
    ]
