# Generated by Django 2.2.6 on 2019-10-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clscurso',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
