# Generated by Django 2.2.6 on 2019-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecuperacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsrecuperacion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
