# Generated by Django 2.2.6 on 2019-10-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClsProfesor',
            fields=[
                ('pk_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('dpi', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.IntegerField()),
                ('fk_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppUsuario.ClsUsuario')),
            ],
        ),
    ]
