# Generated by Django 2.2.6 on 2019-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClsEstablecimiento',
            fields=[
                ('pk_establecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('fundacion', models.DateField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
